---

- hosts: 10.3.1.14
  become: yes
  tasks:
    - name: "Install Dependencies"
      yum:
        name: 
        - python3
        - pip
        state: latest

    - name: "Pip install docker"
      ansible.builtin.pip:
        name: docker

    - name: "Create Dockge Dirs"
      ansible.builtin.file:
        path: /opt/stacks
        state: directory
    
    - name: "Create Dockge Dir2"
      ansible.builtin.file:
        path: /opt/dockge
        state: directory

    - name: "Download Dockge Compose"
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/louislam/dockge/master/compose.yaml
        dest: /opt/dockge/compose.yml
        mode: '0440'
        timeout: 200
    
    - name: "Start Dockge"
      community.docker.docker_compose:
        project_src: /opt/dockge
      register: output