---
- name: Run whoami with elevated privileges
  hosts: all
  become: true
  tasks:
    - name: Run whoami
      command: whoami
      register: whoami_output

    - name: Display whoami output
      debug:
        var: whoami_output.stdout