---
- name: Check Docker container updates
  hosts: fedora
  gather_facts: false
  tasks:
    - name: Get running Docker containers
      shell:
        cmd: "docker ps --format {{.Names}}"
      register: docker_containers
      changed_when: false

    - name: Check for updates in Docker containers
      shell: docker pull {{ item }}
      with_items: "{{ docker_containers.stdout_lines }}"
      ignore_errors: true
      register: docker_pull_output
      changed_when: false

    - name: Display Docker container update status
      debug:
        msg: "Container {{ item.item }} is up to date"
      loop: "{{ docker_pull_output.results }}"
      when: item.rc == 0

    - name: Display Docker container update status
      debug:
        msg: "Container {{ item.item }} needs update"
      loop: "{{ docker_pull_output.results }}"
      when: item.rc != 0
