---
- name: Initialise a new Fedora VM
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  tasks:
    - name: Intial Update and Install of requierd packages
      block:
        - name: Führe DNF Update aus
          ansible.builtin.dnf:
            name: "*"
            state: latest
            update_only: true

        - name: Install qemu-guest-agent
          ansible.builtin.dnf:
            name: qemu-guest-agent
            state: present

        - name: Install required packages
          dnf:
            name: "{{ item }}"
            state: present
          loop:
            - dnf-plugins-core
            - dnf-utils
            - device-mapper-persistent-data
            - lvm2
            - git
            - which
            - stow
            - neovim
            - tmux
            - npm
            - fd-find
            - the_silver_searcher
            - nmap

    - name: Install and enable Docker
      block:
        - name: Add Docker CE repository
          command:
            cmd: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

        - name: Install Docker CE
          dnf:
            name: "{{ item }}"
            state: present
          loop:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose-plugin

        - name: Start Docker service
          service:
            name: docker
            state: started
            enabled: true

        - name: Add user 'nross' to the docker group
          user:
            name: nross
            groups: docker
            append: true

    - name: Add Ansible User
      block:
        - name: Add user 'ansible'
          user:
            name: ansible
            shell: /bin/bash
            password: "$y$j9T$mUpqeDgKh9/bTSQovbkJQ0$TMsoPVAA6aYml0.QsKqByqjk2p169SY2GPNkWXzyK0/"
            groups: wheel, docker
            append: true

        - name: Ensure home dir exists for ansible user
          file:
            path: /home/ansible
            state: directory
            owner: ansible
            group: ansible
            mode: "0700"

        - name: Add SSH key for ansible user
          authorized_key:
            user: ansible
            key: "{{ lookup('file', '/home/semaphore/inventory/ansible.pub') }}"
            state: present
            exclusive: true
          become: true

    - name: Setup dotfiles
      block:
        - name: Set Git user.name
          command: git config --global user.name "NRossmann"
          register: git_user_name
          changed_when: git_user_name.rc != 0

        - name: Set Git user.email
          command: git config --global user.email nrossmann@gmx.de
          register: git_user_email
          changed_when: git_user_email.rc != 0
        
        - name: Ensure 
          file:
            path: /home/ansible/.ssh
            state: directory
            owner: ansible
            group: ansible
            mode: "0700"

        - name: Clone dotfiles repository
          git:
            repo: https://github.com/NRossmann/dotfiles.git
            dest: "/home/nross/dotfiles"
            clone: true

        - name: Delete .bashrc file
          file:
            path: "/home/nross/.bashrc"
            state: absent

        - name: Stow dotfiles
          shell: stow */
          args:
            chdir: "/home/nross/dotfiles"
          when: cd_output is succeeded

    - name: Start Dockge
      block:
        - name: Create directories /opt/dockge and /opt/stacks
          file:
            path: "{{ item }}"
            state: directory
            mode: '0755'
          loop:
            - /opt/dockge
            - /opt/stacks

        - name: Download compose.yaml file
          get_url:
            url: "https://raw.githubusercontent.com/louislam/dockge/master/compose.yaml"
            dest: "/opt/dockge/compose.yml"

        - name: Run docker-compose up
          command: "docker-compose up -d"
          args:
            chdir: "/opt/dockge"
