---

- name: Update alle Pakete
  hosts: all
  become: true
  tasks:
    - name: Führe DNF Update aus
      hosts: rocky, fedora 
      dnf:
        name: "*"
        state: latest
      
    
    - name: Führe Apt Upgrade durch
      hosts: proxmox 
      apt:
        upgrade: yes
      