---

- name: Update alle Pakete
  hosts: all
  become: true
  tasks:
    - name: Führe DNF Update aus
      become: true
      become_method: ansible.builtin.su
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'Fedora'
    - name: Führe Apt Upgrade durch
      become: true
      ansible.builtin.apt:
        upgrade: true
      when: ansible_distribution == 'Debian'
