---

- name: Update alle Pakete
  hosts: all
  become: true
  tasks:
    - name: Führe DNF Update aus
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'Rocky' or ansible_distribution == 'Fedora'
      
    
    - name: Führe Apt Upgrade durch
      apt:
        upgrade: yes
      when: ansible_distribution == 'Debian'
      